<?php
/**
 * Admin: Import WordPress recipes from exported ZIP.
 * Upload ZIP via this page → recipes go to 'pending' status.
 */
// Raise limits for large ZIP uploads before anything else
@ini_set('upload_max_filesize', '256M');
@ini_set('post_max_size',       '256M');
@ini_set('memory_limit',        '512M');
@ini_set('max_execution_time',  '300');

require_once __DIR__ . '/_admin.php';
ensure_recipe_pending_status();

$results = null;
$preview = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_check();
    $action = $_POST['action'] ?? '';

    // ── Preview ZIP before import ────────────────────────────────────────────
    if ($action === 'preview' && !empty($_FILES['zipfile']['name'])) {
        $tmpZip = $_FILES['zipfile']['tmp_name'];
        $zip = new ZipArchive();
        if ($zip->open($tmpZip) !== true) {
            flash('error', 'Could not open ZIP file. Make sure it was generated by the WP Exporter.');
        } else {
            $jsonContent = $zip->getFromName('wp-recipes.json');
            $zip->close();
            if (!$jsonContent) {
                flash('error', 'wp-recipes.json not found in ZIP. Please re-export.');
            } else {
                $data    = json_decode($jsonContent, true);
                $preview = $data;
                // Store ZIP temporarily for the actual import
                $tmpPath = sys_get_temp_dir() . '/ba_wp_import.zip';
                move_uploaded_file($tmpZip, $tmpPath);
                $_SESSION['_wp_import_tmp'] = $tmpPath;
                $_SESSION['_wp_import_ts']  = time();
            }
        }
    }

    // ── Run actual import ────────────────────────────────────────────────────
    if ($action === 'import') {
        csrf_check();
        $tmpPath = $_SESSION['_wp_import_tmp'] ?? '';
        if (!$tmpPath || !file_exists($tmpPath) || (time() - ($_SESSION['_wp_import_ts'] ?? 0)) > 3600) {
            flash('error', 'Import session expired. Please upload the ZIP again.');
            redirect('admin/import-wp.php');
        }

        set_time_limit(300);
        $zip = new ZipArchive();
        if ($zip->open($tmpPath) !== true) { flash('error', 'Could not open ZIP.'); redirect('admin/import-wp.php'); }

        $jsonContent = $zip->getFromName('wp-recipes.json');
        $data        = json_decode($jsonContent, true);
        $recipes     = $data['recipes'] ?? [];

        // Admin user ID
        $adminId = (int)db()->query("SELECT id FROM users WHERE is_admin=1 ORDER BY id LIMIT 1")->fetchColumn();

        $imported = 0; $skipped = 0; $failed = 0;
        $pdo = db();

        foreach ($recipes as $r) {
            // Duplicate check by title
            $dup = $pdo->prepare("SELECT COUNT(*) FROM recipes WHERE title=?");
            $dup->execute([trim($r['title'])]);
            if ($dup->fetchColumn() > 0) { $skipped++; continue; }

            // Handle image
            $imgPath = null;
            if (!empty($r['image'])) {
                $imgData = $zip->getFromName($r['image']);
                if ($imgData) {
                    $ext      = pathinfo($r['image'], PATHINFO_EXTENSION) ?: 'jpg';
                    $imgName  = 'wp_' . ($r['wp_id'] ?? uniqid()) . '.' . $ext;
                    $imgDir   = dirname(__DIR__) . '/uploads/recipes/';
                    if (!is_dir($imgDir)) mkdir($imgDir, 0755, true);
                    file_put_contents($imgDir . $imgName, $imgData);
                    $imgPath = 'uploads/recipes/' . $imgName;
                }
            }

            // Category
            $catId = null;
            if (!empty($r['category'])) {
                $catId = find_or_create('categories', $r['category'], $adminId);
            }

            // Slug
            $slug = slugify($r['title']);
            $slugCheck = $pdo->prepare("SELECT COUNT(*) FROM recipes WHERE slug LIKE ?");
            $slugCheck->execute([$slug . '%']);
            if ($slugCheck->fetchColumn() > 0) $slug .= '-' . substr(bin2hex(random_bytes(2)), 0, 4);

            // Story
            $story = $r['story'] ?? '';

            try {
                $pdo->beginTransaction();

                // Insert recipe
                $prepTime = (int)($r['prep_time'] ?? 0) ?: null;
                $cookTime = (int)($r['cook_time'] ?? 0) ?: null;
                $cuiId    = !empty($r['cuisine']) ? find_or_create('cuisines', $r['cuisine'], $adminId) : null;
                $pdo->prepare(
                    "INSERT INTO recipes (user_id, title, slug, image, story, prep_time, cook_time, category_id, cuisine_id, status, created_at)
                     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?)"
                )->execute([$adminId, $r['title'], $slug, $imgPath, $story ?: null,
                    $prepTime, $cookTime, $catId, $cuiId,
                    $r['published_at'] ?? date('Y-m-d H:i:s')]);
                $recipeId = (int)$pdo->lastInsertId();

                // Insert ingredients
                foreach (($r['ingredients'] ?? []) as $order => $ingLine) {
                    $ingLine = trim($ingLine);
                    if (!$ingLine) continue;
                    // Try to split "200g Paneer" into qty + name
                    if (preg_match('/^([\d\/\.\s]+(?:g|kg|ml|l|cup|tbsp|tsp|piece|pinch|handful|medium|large|small)[s]?\.?)\s+(.+)$/i', $ingLine, $m)) {
                        $qty  = trim($m[1]);
                        $name = trim($m[2]);
                    } else {
                        $qty  = '';
                        $name = $ingLine;
                    }
                    $ingId = find_or_create('ingredients', $name, $adminId);
                    if ($ingId) {
                        $pdo->prepare("INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, sort_order) VALUES (?,?,?,?)")
                            ->execute([$recipeId, $ingId, $qty ?: null, $order]);
                    }
                }

                // Insert steps
                foreach (($r['steps'] ?? []) as $n => $stepText) {
                    $stepText = trim($stepText);
                    if (!$stepText) continue;
                    $pdo->prepare("INSERT INTO recipe_steps (recipe_id, step_no, instruction) VALUES (?,?,?)")
                        ->execute([$recipeId, $n + 1, $stepText]);
                }

                $pdo->commit();
                $imported++;
            } catch (Throwable $e) {
                $pdo->rollBack();
                $failed++;
            }
        }

        $zip->close();
        unlink($tmpPath);
        unset($_SESSION['_wp_import_tmp'], $_SESSION['_wp_import_ts']);

        $results = compact('imported', 'skipped', 'failed');
        flash('success', "Import complete: $imported imported, $skipped skipped (duplicates), $failed failed.");
        redirect('admin/import-wp.php?done=1&imported=' . $imported . '&skipped=' . $skipped . '&failed=' . $failed);
    }
}

// Done redirect
$done = isset($_GET['done']);

$pageTitle = 'Admin · Import WordPress';
include dirname(__DIR__) . '/includes/header.php';
?>
<div class="container section">
  <h1>📥 Import WordPress Recipes</h1>
  <?php admin_nav('import-wp'); ?>

  <?php if ($done): ?>
    <div class="panel" style="text-align:center;padding:40px">
      <div style="font-size:48px;margin-bottom:12px">✅</div>
      <h2>Import Complete!</h2>
      <div style="display:flex;gap:20px;justify-content:center;margin:20px 0;flex-wrap:wrap">
        <div class="stat-card"><strong style="color:var(--green-700)"><?= (int)$_GET['imported'] ?></strong><span>Imported</span></div>
        <div class="stat-card"><strong style="color:var(--ink-soft)"><?= (int)$_GET['skipped'] ?></strong><span>Skipped (duplicates)</span></div>
        <div class="stat-card"><strong style="color:var(--danger)"><?= (int)$_GET['failed'] ?></strong><span>Failed</span></div>
      </div>
      <p class="muted">All imported recipes are in <strong>Pending</strong> status. Review and bulk-approve them from the Content page.</p>
      <a href="<?= e(url('admin/content.php?tab=pending')) ?>" class="btn btn-primary" style="margin-top:8px">Review Pending Recipes →</a>
    </div>

  <?php elseif ($preview): ?>
    <div class="panel">
      <h3>Preview — Ready to Import</h3>
      <div style="display:flex;gap:16px;margin-bottom:20px;flex-wrap:wrap">
        <div class="stat-card"><strong><?= (int)$preview['total'] ?></strong><span>Total recipes</span></div>
        <div class="stat-card"><strong><?= count(array_filter($preview['recipes'], fn($r) => !empty($r['image']))) ?></strong><span>With images</span></div>
        <div class="stat-card"><strong><?= count(array_filter($preview['recipes'], fn($r) => count($r['ingredients']) > 0)) ?></strong><span>With ingredients</span></div>
        <div class="stat-card"><strong><?= count(array_filter($preview['recipes'], fn($r) => count($r['steps']) > 0)) ?></strong><span>With steps</span></div>
      </div>
      <p class="muted">Exported: <?= e($preview['exported_at']) ?> · Source DB: <?= e($preview['wp_db']) ?></p>

      <h4 style="margin-top:20px">Sample (first 5 recipes):</h4>
      <div class="table-wrap">
        <table class="data">
          <tr><th>Title</th><th>Category</th><th>Ingredients</th><th>Steps</th><th>Image</th></tr>
          <?php foreach (array_slice($preview['recipes'], 0, 5) as $r): ?>
            <tr>
              <td><?= e($r['title']) ?></td>
              <td class="small"><?= e($r['category'] ?: '—') ?></td>
              <td><?= count($r['ingredients']) ?></td>
              <td><?= count($r['steps']) ?></td>
              <td><?= $r['image'] ? '✅' : '—' ?></td>
            </tr>
          <?php endforeach; ?>
        </table>
      </div>

      <div style="margin-top:24px;padding:16px;background:var(--orange-100);border-radius:10px">
        <strong>⚠️ This will:</strong>
        <ul style="margin:8px 0 0;padding-left:20px;line-height:2">
          <li>Import <?= (int)$preview['total'] ?> recipes as <strong>Pending</strong> (hidden from public)</li>
          <li>Skip any recipes already in the database (matched by title)</li>
          <li>Set all recipe creators to your Admin account</li>
          <li>Copy all images to uploads/recipes/</li>
        </ul>
      </div>

      <form method="post" style="margin-top:20px">
        <?= csrf_field() ?>
        <input type="hidden" name="action" value="import">
        <button class="btn btn-primary" type="submit"
                onclick="this.textContent='Importing... please wait ⏳ (may take 1-2 min)';this.disabled=true;this.form.submit()">
          🚀 Start Import (<?= (int)$preview['total'] ?> recipes)
        </button>
        <a href="admin/import-wp.php" class="btn btn-ghost" style="margin-left:10px">Cancel</a>
      </form>
    </div>

  <?php else: ?>
    <div class="panel" style="max-width:600px">
      <h3>Step 1 — Run the exporter on your local machine</h3>
      <ol style="line-height:2.2">
        <li>Copy <code>wp-exporter.php</code> to <code>C:\xampp\htdocs\boskets-old\</code></li>
        <li>Visit <a href="http://localhost/boskets-old/wp-exporter.php" target="_blank">http://localhost/boskets-old/wp-exporter.php</a></li>
        <li>Click <strong>Start Export</strong></li>
        <li>Download <strong>wp-boskets-export.zip</strong></li>
      </ol>

      <h3 style="margin-top:24px">Step 2 — Upload the ZIP here</h3>
      <form method="post" enctype="multipart/form-data">
        <?= csrf_field() ?>
        <input type="hidden" name="action" value="preview">
        <label class="field">Select wp-boskets-export.zip
          <input type="file" name="zipfile" accept=".zip" required>
        </label>
        <button class="btn btn-primary" type="submit" style="margin-top:14px">Preview Import</button>
      </form>
    </div>
  <?php endif; ?>
</div>
<?php include dirname(__DIR__) . '/includes/footer.php'; ?>
